# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4VD29mqUzxblqUb2Mi7waOiJW4tr8p7
"""

import streamlit as st
from transformers import pipeline

st.set_page_config(page_title="BERT Sentiment Analyzer", page_icon="🤖")
st.title("🤖 Sentiment Analyzer (Powered by BERT)")
st.markdown("Enter a sentence below and get a high-accuracy sentiment classification using a fine-tuned BERT model.")

# Load once (cached)
@st.cache_resource
def load_model():
    return pipeline("sentiment-analysis")

analyzer = load_model()

# User input
text = st.text_area("Write something...")

if st.button("Analyze"):
    if text:
        with st.spinner("Analyzing..."):
            result = analyzer(text)[0]
            label = result['label']
            score = result['score']

            st.subheader("📊 Result")
            st.write(f"**Sentiment:** {label}")
            st.write(f"**Confidence:** {score:.2f}")
    else:
        st.warning("⚠️ Please enter some text.")